version: '3.7'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.6
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse:/migrations
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: .
    image: validator-risk-api:local
    environment:
      - CLICKHOUSE_URL=${CLICKHOUSE_URL}
    depends_on:
      - clickhouse
    ports:
      - "3000:3000"
